name: Continuous Integration

# The Nyx CI pipeline running on GitHub Actions
#
# The pipeline uses Gradle tasks for each job and in order to make it incremental the cache is used to store
# the various 'build' directories between tasks (considering each job runs on a different fresh node).
# See https://docs.gradle.org/current/userguide/build_cache.html for more on the Gradle Build Cache.

on: [push]

jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Set up the pipeline cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          build/
          **/build/
        key: ${{ runner.os }}-nyx-gradle-${{ github.run_id }}
        #restore-keys: not used here, start from scratch
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Assemble with Gradle
      run: ./gradlew assemble --build-cache --info --stacktrace
    - name: Archive Nyx state file
      uses: actions/upload-artifact@v2
      with:
        name: .nyx-state-${{ github.job }}.json
        path: build/.nyx-state.json
    - name: Archive Jar
      uses: actions/upload-artifact@v2
      with:
        name: jar
        path: '**/build/libs/'

  test:
    needs: assemble
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Set up the pipeline cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          build/
          **/build/
        key: ${{ runner.os }}-nyx-gradle-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-nyx-gradle-${{ github.run_id }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test with Gradle
      run: ./gradlew test --build-cache --info --stacktrace
    - name: Archive Nyx state file
      uses: actions/upload-artifact@v2
      with:
        name: .nyx-state-${{ github.job }}.json
        path: build/.nyx-state.json
  
  check:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Set up the pipeline cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          build/
          **/build/
        key: ${{ runner.os }}-nyx-gradle-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-nyx-gradle-${{ github.run_id }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Check with Gradle
      env:
          # See the top level https://github.com/mooltiverse/nyx/blob/master/CONTRIBUTING.md#contributing-code file for details about passing these values when testing locally
          ORG_GRADLE_PROJECT_gitHubTestUserToken: ${{ secrets.TEST_GITHUB_USER_TOKEN }}   # The test user token to test Nyx GitHub features
          ORG_GRADLE_PROJECT_gitLabTestUserToken: ${{ secrets.TEST_GITLAB_USER_TOKEN }}   # The test user token to test Nyx GitLab features
      run: ./gradlew check --build-cache --info --stacktrace
    - name: Archive Nyx state file
      uses: actions/upload-artifact@v2
      with:
        name: .nyx-state-${{ github.job }}.json
        path: build/.nyx-state.json
    - name: Archive Test Outputs
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: |
          **/build/reports/
          **/build/test-results/

  build:
    needs: [assemble,check]
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Set up the pipeline cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          build/
          **/build/
        key: ${{ runner.os }}-nyx-gradle-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-nyx-gradle-${{ github.run_id }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build --build-cache --info --stacktrace
    - name: Archive Nyx state file
      uses: actions/upload-artifact@v2
      with:
        name: .nyx-state-${{ github.job }}.json
        path: build/.nyx-state.json
    - name: Archive Javadoc
      uses: actions/upload-artifact@v2
      with:
        name: javadoc
        path: '**/build/docs/javadoc/'

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set up the pipeline cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            build/
            **/build/
          key: ${{ runner.os }}-nyx-gradle-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-nyx-gradle-${{ github.run_id }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish with Gradle
        env:
          # See the top level https://github.com/mooltiverse/nyx/blob/master/CONTRIBUTING.md#contributing-code file for details about passing these values when testing locally
          ORG_GRADLE_PROJECT_gitHubUser: ${{ secrets.GITHUB_USERNAME }}
          ORG_GRADLE_PROJECT_gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.MAVEN_USER }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.MAVEN_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKeyBase64: ${{ secrets.GPG_PRIVATE_KEY_BASE64 }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPC_PASSPHRASE }}
          ORG_GRADLE_PROJECT_gradlePublishKey: ${{ secrets.GRADLE_PLUGIN_PUBLISH_KEY }}
          ORG_GRADLE_PROJECT_gradlePublishSecret: ${{ secrets.GRADLE_PLUGIN_PUBLISH_SECRET }}
        run: ./gradlew publish --build-cache --info --stacktrace
      - name: Archive Nyx state file
        uses: actions/upload-artifact@v2
        with:
          name: .nyx-state-${{ github.job }}.json
          path: build/.nyx-state.json

  release:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set up the pipeline cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            build/
            **/build/
          key: ${{ runner.os }}-nyx-gradle-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-nyx-gradle-${{ github.run_id }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Release with Gradle
        env:
          # See the top level https://github.com/mooltiverse/nyx/blob/master/CONTRIBUTING.md#contributing-code file for details about passing these values when testing locally
          ORG_GRADLE_PROJECT_gitHubUser: ${{ secrets.GITHUB_USERNAME }}
          ORG_GRADLE_PROJECT_gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew release --build-cache --info --stacktrace
      - name: Archive Nyx state file
        uses: actions/upload-artifact@v2
        with:
          name: .nyx-state-${{ github.job }}.json
          path: build/.nyx-state.json
